project:
  type: website

website:
  title: "The Data Nurse"
  search: false
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects
        menu: 
          - text: Social media and Mental health
            href: social_media.qmd
      - text: Blog
        menu: 
          - text: Building my first website
      - text: Poems
        menu: 
          - text: Unheard
            href: poem_unheard.qmd
          - text: Unspoken Apologies
            href: poem_unspoken.qmd
    tools: 
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/tosan-okome
          - text: Report a Bug
            href: https://github.com/tosan-okome

format:
  html:
    theme: 
      light: minty
      dark: solar

